- mocks/data/cms.tsx
- src/app/[locale]/(logged-out)/about/components/AboutContent/AboutContent.tsx
- src/app/[locale]/(logged-out)/about/components/AboutContent/index.ts
- src/app/[locale]/(logged-out)/about/layout.tsx
- src/app/[locale]/(logged-out)/about/page.tsx
- src/app/[locale]/(logged-out)/components/FeatureBox/FeatureBox.tsx
- src/app/[locale]/(logged-out)/components/FeatureBox/index.ts
- src/app/[locale]/(logged-out)/components/InfoPageWrapper/InfoPageWrapper.tsx
- src/app/[locale]/(logged-out)/components/InfoPageWrapper/index.ts
- src/app/[locale]/(logged-out)/features/components/FeaturesContent/FeaturesContent.tsx
- src/app/[locale]/(logged-out)/features/components/FeaturesContent/index.ts
- src/app/[locale]/(logged-out)/features/layout.tsx
- src/app/[locale]/(logged-out)/features/page.tsx
- src/config/locales/en.json
- src/config/theme.ts
- src/consts/router.ts
- src/modules/Footer/Footer.tsx
- src/modules/NavBar/NavBar.test.tsx
- src/modules/NavBar/NavBar.tsx
- src/types/router.ts
https://github.com/user-attachments/assets/2c2e7719-feef-4a6b-9d75-4e43380fcc65
Supported by shared components. Update nav bar and footer links.
https://hdruk.atlassian.net/browse/SOURSD-938
> feat(SOURSD-938): Add About and Feature pages

- mocks/data/cms.tsx
- src/app/[locale]/(logged-in)/data-custodian/profile/components/UserTrainingAccreditations/UserTrainingAccreditations.tsx
- src/app/[locale]/(logged-in)/user/profile/components/AffiliationsPage/AffiliationsPage.tsx
- src/app/[locale]/(logged-in)/user/profile/components/Experience/Experience.tsx
- src/app/[locale]/(logged-in)/user/profile/components/Home/Home.tsx
- src/app/[locale]/(logged-in)/user/profile/components/Identity/Identity.tsx
- src/app/[locale]/(logged-in)/user/profile/components/ProjectsSafeProject/ProjectsSafeProject.tsx
- src/app/[locale]/(logged-in)/user/profile/components/SubPageProjects/SubPageProjects.tsx
- src/app/[locale]/(logged-in)/user/profile/components/Trainings/Trainings.tsx
- src/components/FormSection/FormSection.tsx
- src/components/Guidance/Guidance.styles.ts
- src/components/GuidanceDrawer/Guidance.styles.ts
- src/consts/router.ts
- src/modules/ProfessionalRegistrations/ProfessionalRegistrations.tsx
- src/modules/ProfessionalRegistrations/index.ts
- src/modules/ProjectsSafePeople/ProjectsSafePeople.tsx
- src/modules/Training/Training.tsx
- src/types/router.ts
Updated copy
Improved formatting and alignment
User table for Users does not contain links to other users' details:
... custodians and organisations do have links:
- Update User homepage copy
- Update content and formatting of mockedResearcherAffiliationsGuidance
- Improve the formatting of Experience page
- Improve formatting/padding of forms
- Fix links and text for navigating back and forward through user profile pages.
- Fix sensible widths for Professional Registrations and Training tables
- Modify/control link destination from clicking on user name in ProjectsSafePeople table based on logged in user's role.
https://hdruk.atlassian.net/browse/SOURSD-904
> feat(SOURSD-904): Various improvements to User profile pages

- src/app/[locale]/(logged-in)/data-custodian/profile/components/UserHistory/UserHistory.tsx
- src/components/MaskLabel/MaskLabel.tsx
- src/config/locales/en.json
- src/services/users/getUserHistory.ts
- src/services/users/getUserQueryHistory.ts
- src/services/users/index.ts
- src/services/users/types.ts
Needs a placeholder for user history
https://hdruk.atlassian.net/browse/SOURSD-953
> feat(SOURSD-953): Add a placeholder for user history section

- src/app/[locale]/(logged-in)/data-custodian/profile/users/[id]/projects/[projectId]/[subTabId]/components/CustodianProjectUser/CustodianProjectUser.tsx
- src/app/[locale]/(logged-in)/organisation/profile/user-administration/[subTabId]/[id]/[subSubTabId]/components/OrganisationUser/OrganisationUser.tsx
- src/components/UserDetails/UserDetails.tsx
- src/components/UserDetails/index.ts
https://github.com/user-attachments/assets/be347949-31e5-4cc6-8c54-4c53f1ca8e03
Adds user details component showing name, avatar and email address.
https://hdruk.atlassian.net/browse/SOURSD-997
> feat(SOURSD-997): Add User details component

- src/app/[locale]/(logged-out)/cookie-policy/components/CookiePolicy/CookiePolicy.tsx
- src/app/[locale]/(logged-out)/privacy-policy/components/PrivacyPolicy/PrivacyPolicy.tsx
- src/components/Markdown/Markdown.tsx
https://hdruk.atlassian.net/browse/SOURSD-1030
> fix(SOURSD-1030): Updating styling for markdown rendering of policy pages

- src/app/[locale]/(logged-in)/data-custodian/profile/components/Contacts/Contacts.tsx
- src/components/ProjectsAddUserForm/ProjectsAddUserForm.tsx
- src/modules/OrganisationUsersFilters/OrganisationUsersFilters.tsx
- src/modules/ProjectsSafePeople/ProjectsSafePeople.tsx
https://github.com/user-attachments/assets/87d787ab-fbec-4aec-9e56-cdb0fd39343f
Search wasnt working correctly for searching by name
> fix(SOURSD-1011): Switch to search by full name

- src/hooks/usePaginatedQuery/usePaginatedQuery.tsx
- src/modules/ProjectsFilters/ProjectsFilters.tsx
- src/modules/SearchActionMenu/SearchActionMenu.tsx
- src/services/custodians/getCustodiansUserProjects.ts
- src/services/projects/getEntityProjects.ts
- src/types/query.ts
- src/utils/query.ts
https://github.com/user-attachments/assets/6da842ce-ce61-4abc-ab68-bd3b00301a21
* Fixes to get filtering working as it should do
https://hdruk.atlassian.net/browse/SOURSD-1010
> fix(SOURSD-1010): Filtering of projects by custodian based on state

- src/app/[locale]/(logged-in)/organisation/profile/hooks/usePatchOrganisation.tsx
- src/config/locales/en.json
- src/services/requestHelpers.ts
Display a better error message when there is a 403 response 
https://hdruk.atlassian.net/browse/SOURSD-1035
> fix(SOURSD-1035): Handle forbidden errors

- src/components/FieldsToText/FieldsToText.tsx
- src/config/locales/en.json
- src/modules/ProjectsSafeDataForm/ProjectsSafeDataForm.tsx
- src/utils/form.ts
* fix 1
* fix 2
* Form for dates not working
https://hdruk.atlassian.net/browse/SOURSD-1034
> fix(SOURSD-1034): Clean up mess with dates not working 

- src/app/[locale]/(logged-in)/organisation/profile/components/Home/Home.tsx
- src/hooks/useAuth/useAuth.ts
- src/hooks/useRegisterUser/userRegisterUser.ts
- src/modules/NavBar/NavBar.tsx
- src/types/application.ts
- src/utils/application.ts
https://hdruk.atlassian.net/browse/SOURSD-1007
> feat(SOURSD-1007): Fix showing soursd ID for organisation created

- src/app/[locale]/(logged-in)/data-custodian/profile/components/Rules/Rules.tsx
- src/services/custodians/putCustodianActiveEntityModel.ts
> fix(SOURSD-1343): Fix saving of custodian rules

- src/app/[locale]/(logged-in)/data-custodian/profile/components/Organisations/Organisations.tsx
> fix(SOURSD-1561): Fix to route bug

- src/modules/ProjectsFilters/ProjectsFilters.test.tsx
- src/modules/ProjectsFilters/ProjectsFilters.tsx
https://github.com/user-attachments/assets/71756223-9ebf-4231-82ce-43cb05f6913e
Fixes for filtering
https://hdruk.atlassian.net/browse/REGISTRY-1568?atlOrigin=eyJpIjoiODU5YjZjMWE4MTc1NGQ0OWJmM2RiODAyZDllMDc4M2UiLCJwIjoiaiJ9
> fix(REGISTRY-1568): Fix for project date filters

- jest.setup.tsx
- src/config/locales/en.json
- src/organisms/ActionLogUpdater/ActionLogUpdater.test.tsx
- src/organisms/ActionLogUpdater/ActionLogUpdater.tsx
- src/organisms/ActionLogUpdater/index.ts
- src/organisms/ActionLogs/ActionLogs.test.tsx
- src/organisms/ActionLogs/ActionLogs.tsx
- src/organisms/ActionLogs/utils.tsx
- src/organisms/Application/Application.tsx
- src/organisms/ApplicationData/ApplicationData.tsx
- src/services/action_logs/index.ts
- src/services/action_logs/putActionLog.ts
- src/services/action_logs/putActionLogQuery.ts
https://github.com/user-attachments/assets/25ff2fa9-1892-4ebe-9556-58332aff8e2d
* Mark as done when has clicked through to mark action as complete
https://hdruk.atlassian.net/browse/REGISTRY-1490
> fix(REGISTRY-1490): Mark as done upon navigation to page

- src/config/locales/en.json
- src/modules/OrganisationsSubsidiariesTable/OrganisationsSubsidiariesTable.tsx
Fix typo and styling issue
Add missing translation
https://hdruk.atlassian.net/browse/REGISTRY-1614
> fix(REGISTRY-1614): Subsidiary typo and styling

- src/organisms/ProjectUsers/ProjectUsers.tsx
Stop button expanding to two lines
https://hdruk.atlassian.net/browse/REGISTRY-1432
> fix(REGISTRY-1432): Button styling

- src/modules/KanbanBoard/KanbanBoard.tsx
Fix max height of kanban board
https://hdruk.atlassian.net/browse/REGISTRY-1602
> feat(REGISTRY-1602): Fix max height of kanban board

- src/app/[locale]/(logged-in)/data-custodian/profile/components/Home/Home.tsx
Increase home intro spacing
https://hdruk.atlassian.net/browse/REGISTRY-1766
> feat(REGISTRY-1766): Increase home intro spacing

- mocks/data/cms.tsx
- src/app/[locale]/(logged-in)/data-custodian/profile/components/SubPage/SubPage.tsx
- src/app/global.css
- src/config/locales/en.json
- Add guidance for configuration page
- Formatting
https://hdruk.atlassian.net/browse/REGISTRY-797
> chore(REGISTRY-797): Add guidance for configuration page

- src/app/[locale]/(logged-in)/organisation/profile/components/NameAndAddress/NameAndAddress.test.tsx
- src/app/[locale]/(logged-in)/organisation/profile/components/NameAndAddress/NameAndAddress.tsx
- src/app/[locale]/(logged-in)/organisation/profile/components/TabsSections/TabsSections.tsx
- src/types/application.ts
Disable org tabs if not system approved
https://hdruk.atlassian.net/browse/REGISTRY-1798
> feat(REGISTRY-1798): Disable org tabs if not system approved

- src/config/locales/en.json
Copy update
https://hdruk.atlassian.net/browse/REGISTRY-1903?atlOrigin=eyJpIjoiZjkwMTUwZjZkYTg1NDAzNWIwOTU0ZjRjMDdjZTY5YTQiLCJwIjoiaiJ9
> chore(REGISTRY-1903): Copy update

- .github/workflows/dev_deployment.yaml
- src/components/ProjectsAddUserForm/ProjectsAddUserForm.tsx
- src/types/application.ts
Display professional email in add user table
https://hdruk.atlassian.net/browse/REGISTRY-1926
> fix(REGISTRY-1665): Display professional email in table
